# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_path', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('bow_hist', models.BinaryField(null=True)),
                ('color_hist', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bow_voc', models.BinaryField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
